name: Mi Laboratorio - SBOM (Dependencias)

on:
  workflow_dispatch: # Lo activamos con el botón verde manual

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Clonar mi codigo de FideBurguesas
        uses: actions/checkout@v4

      - name: 2. Instalar Syft (Generador)
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: 3. Instalar Trivy (Escáner)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: 4. Generar Inventario de Software
        run: syft packages dir:. -o cyclonedx-json > mi-sbom.json

      - name: 5. Analizar librerías (Modo permisivo para pruebas)
        run: trivy sbom mi-sbom.json
